---
- hosts: all
  become: yes
  tasks:
  - name: i want to install web server on ubuntu node
    apt:
      name: apache2
      state: present
  - name: i want to instll tree
    apt:
      name: tree
      state: present
  - name: i want to instll git
    apt:
      name: git
      state: present