---
- hosts: all
  become: yes
  tasks:
  - name: i want to install web server on ubuntu node
    apt:
      name: apache2
      state: present
  - name: i want to restart webservers on ubuntu node
    service:
      name: apache2
      state: restarted