---
- hosts: webserver
  become: yes
  tasks:
    - name: i want to instll webserver on Debian only
      apt:
        name: "{{ mywebpackageforubuntu }}"
        state: present
      when: ansible_os_family == "Debian"
    
    - name: I want to start webservice on ubuntu
      service:
        name: "{{ mywebpackageforubuntu }}"
        state: stoped
      when: ansible_os_family == "Debian"

    - name: I want to install webserver on redhat only
      yum:
        name: "{{ mywebpackageforredhat }}"
        state: present
      when: ansible_os_family == "redhat"

    - name: I want to start webservice on redhat
      service:
        name: "{{ mywebpackageforredhat }}"
        state: restarted
      when: ansible_os_family == "redhat"

